### PR TITLE
Fix the assignment mistake in flags

### PR DESCRIPTION
**Pull request by yuexiao-wang**
Fix the assignment mistake int flags which the signe  '='  is missed.

Please check it and thanks!

### CODE REVIEW

**Comment by idanmo** [comment]
Hi,
Please squash your commits.

**Comment by nir0s** [comment]
LTGM, I'll merge after squash

**Comment by yuexiao-wang** [comment]
Hi  nir0s,
I'm not sure I understand your comment.
what do you mean by "I'll merge after squash?
 I need to  rebase the branch on my fork, add my commits, and then send a new pull request.

**Comment by yuexiao-wang** [comment]
Got it，and I will squash my commits

**Comment by yuexiao-wang** [comment]
Hi, nir0s,

I have squashed my commits and please check it.
cc @nir0s 

Thanks!

**Pull request merged**
