### PR TITLE
Add Insights widget docs

### PR DESCRIPTION
**Pull request by bmansheim**

### CODE REVIEW

**Comment by bmansheim** [comment]
stage-docs.getcloudify.org/insights-widget/manager_webui/insights-widget/

**Comment by qooban** [comment]
@talisela Insights widget is not a part of official Cloudify. Not sure, but maybe it's here: https://github.com/mistio/Cloudify-UI-Widget-boilerplate/tree/master/widgets/Insights
Do we want to add it to *cloudify-stage*?

**Comment by bmansheim** [comment]
@qooban You're right. We'll put it somewhere else.

**Comment by bmansheim** [comment]
Moved insights information to the manager section. Over the next couple of months we'll revamp the structure of the docs and find a better place to put this.

**Comment by qooban** [comment]
@bmansheim For me it does not matter where that will be placed. We should only be sure that it is described as a widget which is not built-in in all versions.

**Pull request merged**
