### PR TITLE
Fix kubernetes blueprint name

### PR DESCRIPTION
**Pull request by conkiztador**

### CODE REVIEW

**Comment by EarthmanT** [comment]
The correct blueprint name is [`azure.yaml`](https://github.com/cloudify-examples/simple-kubernetes-blueprint/blob/750aad1bcdb67a100a5cf3853c21660372043b9e/azure.yaml).

**Comment by conkiztador** [comment]
@EarthmanT Docs currently say `azure-blueprint.yaml`.

**Comment by EarthmanT** [comment]
@bmansheim Isn't `4.3.0-build` supposed to get updates made to master as well?

**Comment by bmansheim** [comment]
Fixed in https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/834

**Pull request closed without merging**
