### PR TITLE
RD-6922 Removed information about stage version number

### PR DESCRIPTION
**Pull request by Vorbert-Kruk**
## Description
After merging [#2441 in stage](https://github.com/cloudify-cosmo/cloudify-stage/pull/2441) number version will no longer be visible on the sidebar
As there are some documentation pieces, which are referring to this functionality, they should be updated accordingly

## Changes
- Updated screenshots (8502a1c5a983fefd5f6421b888a11f1688575b92)
- Removed information about displaying version number on stage sidebar (1775bdd6f21afa0faba0f88117e5085df4ffb243)

### CODE REVIEW

**Comment by qooban** [comment]
@Vorbert-Kruk Please also update `widgets-components.md` file (according to: https://github.com/cloudify-cosmo/cloudify-stage/blob/d098244b0557f825d16a82f5a0880e8747caf103/app/components/basic.ts#L1-L6).

**Comment by Vorbert-Kruk** [comment]
> @Vorbert-Kruk Please also update `widgets-components.md` file (according to: https://github.com/cloudify-cosmo/cloudify-stage/blob/d098244b0557f825d16a82f5a0880e8747caf103/app/components/basic.ts#L1-L6).

Will do
Thanks for an apt remark 💪

**Comment by Vorbert-Kruk** [comment]
> @Vorbert-Kruk Please also update `widgets-components.md` file (according to: https://github.com/cloudify-cosmo/cloudify-stage/blob/d098244b0557f825d16a82f5a0880e8747caf103/app/components/basic.ts#L1-L6).

@qooban it seems like `widgets-components.md` file doesn't require update from my changes
[On the docs](https://docs.cloudify.co/latest/developer/writing_widgets/widgets-components/) there are no references to `ProductVersion` component, which I've removed from the `Stage.Basic` namespace
Because of that I assume that no additional changes are required

WDYT?
Maybe you had in mind a different kind of adjustment 🤔

**Comment by qooban** [comment]
@Vorbert-Kruk Oh, I see, we have a gap there. Anyways - no update needed in that case.

**Review by kubama — APPROVED** [review]

**Comment by Vorbert-Kruk** [comment]
@alexmolev as I've got approval from team members, we should be good to go with merging this one 💪

**Pull request merged**
